// Aggregate results/<scenario>-<lang>-r<rep>/summary.json into results/benchmark.md and results/benchmark.json.
//   node --experimental-strip-types --no-warnings bench/aggregate.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./kernel-client.ts";

const dir = join(ROOT, "results");
const LANGS = ["js", "clojure", "elixir", "smalltalk", "racket", "lean"];
const runs = readdirSync(dir)
	.filter((d) => /-r\d+$/.test(d) && existsSync(join(dir, d, "summary.json")))
	.map((d) => JSON.parse(readFileSync(join(dir, d, "summary.json"), "utf8")));

const sum = (xs: number[]) => xs.reduce((a, b) => a + b, 0);
const mean = (xs: number[]) => (xs.length ? sum(xs) / xs.length : NaN);
const f1 = (x: number) => (Number.isNaN(x) ? "-" : x.toFixed(1));
const rows: Record<string, unknown>[] = [];
let md = "# DeepSeek grows the same apps in six kernels\n\nGenerated by `bench/aggregate.ts`. Model: deepseek-flash, output cap 32000 tokens. Each cell is over all repetitions (n).\n";
for (const scenario of ["expenses", "gateway"]) {
	md += `\n## ${scenario}\n\n| kernel | n | hidden goal checks | final regression | develops / run | didn't load | user corrections / run | output tokens / run | minutes / run | cap hits |\n|---|---|---|---|---|---|---|---|---|---|\n`;
	for (const lang of LANGS) {
		const rs = runs.filter((r) => r.lang === lang && r.scenario === scenario);
		if (!rs.length) continue;
		const goalOk = sum(rs.map((r) => r.goal_ok)), goalN = sum(rs.map((r) => r.goal_n));
		const fin = rs.map((r) => r.final_regression.split("/").map(Number));
		const finOk = sum(fin.map((x: number[]) => x[0])), finN = sum(fin.map((x: number[]) => x[1]));
		const row = {
			scenario, lang, n: rs.length,
			goal: `${goalOk}/${goalN}`, goal_pct: Math.round((100 * goalOk) / goalN),
			final: `${finOk}/${finN}`, final_pct: Math.round((100 * finOk) / finN),
			develops: mean(rs.map((r) => r.develops)), load_errors: sum(rs.map((r) => r.load_errors)),
			corrections: mean(rs.map((r) => r.corrections)), out_tokens: mean(rs.map((r) => r.usage?.completion ?? 0)),
			minutes: mean(rs.map((r) => r.minutes)), cap_hits: sum(rs.map((r) => r.max_tokens_hits ?? 0)),
			per_run_goal: rs.map((r) => `${r.goal_ok}/${r.goal_n}`),
		};
		rows.push(row);
		md += `| ${lang} | ${row.n} | ${row.goal} (${row.goal_pct}%) | ${row.final} (${row.final_pct}%) | ${f1(row.develops)} | ${row.load_errors} | ${f1(row.corrections)} | ${Math.round(row.out_tokens)} | ${f1(row.minutes)} | ${row.cap_hits} |\n`;
	}
}
md += "\nHidden goal checks: after each turn, the scenario's own examples run on the live code and are compared with the intended program (the model never sees them). Final regression: every turn's examples against the final intended program, on the final code. Didn't load: develops whose forms did not parse/compile/elaborate.\n";
writeFileSync(join(dir, "benchmark.md"), md);
writeFileSync(join(dir, "benchmark.json"), `${JSON.stringify(rows, null, 2)}\n`);
console.log(md);
