#!/usr/bin/env python3
"""Derives KernelGateway.lean from Kernel.lean: same kernel, gateway prelude, gateway invariants."""
import os, re
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.join(here, "..")
s = open(os.path.join(root, "Kernel.lean")).read()
s = s.replace("import Chat.Prelude", "import Chat.Gateway").replace("`Chat.Prelude", "`Chat.Gateway")
inv = '''/-! ## The gateway scenario's five invariants, on JSON states -/

def sumTokens (calls : Array Json) (key : String) : Int :=
  calls.foldl (fun a c => match c.getObjVal? "key", c.getObjVal? "tokens" with
    | .ok (.str k), .ok (.num n) => if k == key then a + n.mantissa else a
    | _, _ => a) 0

def invariantViolations (s : Json) : List String := Id.run do
  let mut out := []
  let some o := s.getObj?.toOption | return ["state is not an object"]
  for (k, _) in o.toArray do
    if k != "calls" && k != "prices" && k != "quotas" then out := out ++ [s!"known-keys: unexpected key {k}"]
  let mut calls : Array Json := #[]
  match s.getObjVal? "calls" with
  | .error _ => pure ()
  | .ok (.arr cs) =>
    calls := cs
    for c in cs do
      let ok := match c with
        | .obj co =>
          co.toArray.size == 3 &&
          (match co.get? "key" with | some (.str k) => k != "" | _ => false) &&
          (match co.get? "model" with | some (.str k) => k != "" | _ => false) &&
          (match co.get? "tokens" with | some (.num n) => n.exponent == 0 && 0 < n.mantissa | _ => false)
        | _ => false
      if !ok then out := out ++ [s!"calls-shape: bad call {sh c}"]
  | .ok _ => out := out ++ ["calls-shape: calls is not an array"]
  match s.getObjVal? "prices" with
  | .error _ => pure ()
  | .ok (.obj po) =>
    for (k, v) in po.toArray do
      match v with
      | .num n => if n.mantissa < 0 then out := out ++ [s!"prices-shape: price {k} is negative"]
      | _ => out := out ++ [s!"prices-shape: price {k} is not a number"]
  | .ok _ => out := out ++ ["prices-shape: prices is not an object"]
  match s.getObjVal? "quotas" with
  | .error _ => pure ()
  | .ok (.obj qo) =>
    for (k, v) in qo.toArray do
      match v with
      | .num n =>
        if n.mantissa < 0 || n.exponent != 0 then out := out ++ [s!"quotas-shape: quota {k} is not a whole number >= 0"]
        else if sumTokens calls k > n.mantissa then out := out ++ [s!"within-quota: {k} used {sumTokens calls k} of {n.mantissa}"]
      | _ => out := out ++ [s!"quotas-shape: quota {k} is not a number"]
  | .ok _ => out := out ++ ["quotas-shape: quotas is not an object"]
  return out

'''
a = s.index("/-! ## The scenario's three invariants")
b = s.index("/-! ## Static gate")
s = s[:a] + inv + s[b:]
s = s.replace('add "expenses" (Json.arr #[]) (add "budgets" (Json.mkObj []) j)', 'add "calls" (Json.arr #[]) (add "prices" (Json.mkObj []) (add "quotas" (Json.mkObj []) j))')
s = s.replace("Live kernel for chat-grown software, in Lean 4 (PROTOCOL.md v1).", "GENERATED by tools/gen_kernel_gateway.py from Kernel.lean (gateway scenario).\nLive kernel for chat-grown software, in Lean 4 (PROTOCOL.md v1).")
open(os.path.join(root, "KernelGateway.lean"), "w").write(s)
