//! The strive wire protocol.
//!
//! Clients (the TUI, the Electron app, the agent host, headless runs) talk to
//! `strived` with JSON-RPC 2.0, one JSON object per line, over a Unix socket.
//! Every method is declared once in [`methods!`]; that declaration produces the
//! Rust types, the [`Method`] impl and the TypeScript `Methods` map, so the two
//! sides cannot drift without the drift check failing.

pub mod rpc;

use serde::{Deserialize, Serialize, de::DeserializeOwned};
use ts_rs::TS;

/// Bumped on any incompatible change. Clients and daemon must agree exactly.
pub const PROTOCOL_VERSION: u32 = 1;

/// A request method: its wire name plus parameter and result types.
pub trait Method {
    const NAME: &'static str;
    type Params: Serialize + DeserializeOwned;
    type Result: Serialize + DeserializeOwned;
}

macro_rules! methods {
    ($($ty:ident = $name:literal ($params:ty) -> $result:ty;)*) => {
        $(
            #[doc = concat!("The `", $name, "` method.")]
            pub enum $ty {}
            impl Method for $ty {
                const NAME: &'static str = $name;
                type Params = $params;
                type Result = $result;
            }
        )*

        /// Every method name, in declaration order.
        pub const METHOD_NAMES: &[&str] = &[$($name),*];

        /// TypeScript source for the `Methods` map used by the typed client.
        pub fn typescript_methods() -> String {
            let mut imports = std::collections::BTreeSet::new();
            let mut body = String::new();
            $(
                for t in [<$params as TS>::name(&ts_rs::Config::default()), <$result as TS>::name(&ts_rs::Config::default())] {
                    if t != "null" { imports.insert(t); }
                }
                body.push_str(&format!(
                    "  {:?}: {{ params: {}; result: {} }};\n",
                    $name,
                    <$params as TS>::name(&ts_rs::Config::default()),
                    <$result as TS>::name(&ts_rs::Config::default()),
                ));
            )*
            let mut out = String::from("// Generated by strive-proto. Do not edit.\n");
            for t in imports {
                out.push_str(&format!("import type {{ {t} }} from \"./{t}\";\n"));
            }
            out.push_str("\nexport type Methods = {\n");
            out.push_str(&body);
            out.push_str("};\n\nexport type MethodName = keyof Methods;\n");
            out.push_str(&format!("\nexport const PROTOCOL_VERSION = {};\n", PROTOCOL_VERSION));
            out
        }
    };
}

methods! {
    Initialize = "initialize" (InitializeParams) -> InitializeResult;
    DaemonStatus = "daemon/status" (Empty) -> DaemonStatusResult;
    DaemonShutdown = "daemon/shutdown" (Empty) -> Empty;
    SessionCreate = "session/create" (SessionCreateParams) -> SessionInfo;
    SessionList = "session/list" (SessionListParams) -> SessionListResult;
    SessionAttach = "session/attach" (SessionAttachParams) -> SessionAttachResult;
    SessionPrompt = "session/prompt" (SessionPromptParams) -> SessionPromptResult;
    SessionRead = "session/read" (SessionRef) -> SessionReadResult;
}

/// A server-to-client notification: its wire name plus payload type.
pub trait Notification {
    const NAME: &'static str;
    type Params: Serialize + DeserializeOwned;
}

macro_rules! notifications {
    ($($(#[$doc:meta])* $ty:ident = $name:literal ($params:ty);)*) => {
        $(
            $(#[$doc])*
            pub enum $ty {}
            impl Notification for $ty {
                const NAME: &'static str = $name;
                type Params = $params;
            }
        )*

        /// TypeScript source for the `Notifications` map.
        pub fn typescript_notifications() -> String {
            let mut out = String::from("// Generated by strive-proto. Do not edit.\n");
            $(
                let t = <$params as TS>::name(&ts_rs::Config::default());
                out.push_str(&format!("import type {{ {t} }} from \"./{t}\";\n"));
            )*
            out.push_str("\nexport type Notifications = {\n");
            $(
                out.push_str(&format!("  {:?}: {};\n", $name, <$params as TS>::name(&ts_rs::Config::default())));
            )*
            out.push_str("};\n\nexport type NotificationName = keyof Notifications;\n");
            out
        }
    };
}

notifications! {
    /// A new entry in a session this connection attached to.
    SessionEntry = "session/entry" (SessionEntryNotification);
}

/// Parameters or result with no fields. Serializes as `{}`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Empty {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ClientInfo {
    /// For example `strive-tui`, `strive-desktop`, `strive-host`.
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InitializeParams {
    pub protocol_version: u32,
    pub client: ClientInfo,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ServerInfo {
    pub version: String,
    /// Identifies the exact daemon binary, so a rebuilt or upgraded `strive`
    /// can tell that the running daemon is stale.
    pub build: String,
    pub pid: u32,
    pub started_at_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InitializeResult {
    pub protocol_version: u32,
    pub server: ServerInfo,
    /// The strive home directory, `~/.strive` unless `STRIVE_HOME` is set.
    pub home: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DaemonStatusResult {
    pub server: ServerInfo,
    pub uptime_ms: u64,
    /// Connected clients, including the caller.
    pub clients: u32,
    /// Seconds with no clients before the daemon exits.
    pub idle_exit_secs: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionInfo {
    pub id: String,
    pub cwd: String,
    pub created_at_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionCreateParams {
    pub cwd: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionListParams {
    /// Only sessions started in this directory. All sessions when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub cwd: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionListResult {
    /// Newest first.
    pub sessions: Vec<SessionInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionRef {
    pub id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionAttachParams {
    pub id: String,
    /// Return only entries after this seq (for catching up after a reconnect).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub after_seq: Option<u64>,
}

/// History up to now. Later entries arrive as `session/entry` notifications.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionAttachResult {
    pub session: SessionInfo,
    pub entries: Vec<Entry>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionPromptParams {
    pub id: String,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionPromptResult {
    pub seq: u64,
}

/// A session's journal as it is on disk, and whether it verifies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionReadResult {
    pub session: SessionInfo,
    /// The entries that verified, in order.
    pub entries: Vec<Entry>,
    pub committed: u64,
    /// Bytes of a partial last line left by a crash; discarded on next open.
    pub torn_bytes: u64,
    /// Why verification failed. Absent when the journal is intact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub problem: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionEntryNotification {
    pub session_id: String,
    pub entry: Entry,
}

/// The SHA-256 of a blob in the content store, written `sha256:<64 lowercase hex>`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, TS)]
#[ts(export, type = "string")]
pub struct Digest([u8; 32]);

impl Digest {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    pub fn parse(s: &str) -> Option<Self> {
        let hex = s.strip_prefix("sha256:")?;
        if hex.len() != 64 || hex.bytes().any(|b| b.is_ascii_uppercase()) {
            return None;
        }
        let mut out = [0u8; 32];
        hex::decode_to_slice(hex, &mut out).ok()?;
        Some(Self(out))
    }

    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// The 64-character lowercase hex form, without the `sha256:` prefix.
    pub fn hex(&self) -> String {
        hex::encode(self.0)
    }
}

impl std::fmt::Display for Digest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "sha256:{}", self.hex())
    }
}

impl Serialize for Digest {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.collect_str(self)
    }
}

impl<'de> Deserialize<'de> for Digest {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = String::deserialize(d)?;
        Digest::parse(&s).ok_or_else(|| serde::de::Error::custom(format!("not a sha256 digest: {s:?}")))
    }
}

/// Something that happened in a session. Journaled in order; never edited.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum Event {
    SessionStarted {
        /// Journal format version.
        format: u32,
        cwd: String,
        strive_version: String,
    },
    UserMessage {
        text: String,
    },
    /// Opening the journal found a partial last line from a crash and
    /// discarded it.
    Recovered {
        discarded_bytes: u64,
    },
    /// The session's spending limits from here on. `None` means unlimited.
    BudgetSet {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        usd_micros: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        tokens: Option<u64>,
    },
    /// A model request was admitted against the budget and sent upstream.
    /// Written before sending, so a crash mid-call still counts it.
    ModelCallStarted {
        /// Numbers this session's calls; pairs with `ModelCallFinished`.
        call: u64,
        provider: String,
        model: String,
        /// The exact request body sent upstream.
        request: Digest,
        /// The most this call can cost, held until it finishes.
        reserved_usd_micros: u64,
        reserved_tokens: u64,
    },
    ModelCallFinished {
        call: u64,
        outcome: CallOutcome,
        /// The exact response bytes received, when any were.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        response: Option<Digest>,
        duration_ms: u64,
    },
}

/// How a model call ended, and what it cost.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum CallOutcome {
    /// The provider reported usage; the cost is exact.
    Complete { status: u16, usage: Usage, cost_usd_micros: u64 },
    /// The provider refused the request before doing work (an error status).
    Rejected { status: u16 },
    /// The call broke after it may have been billed. It is charged the full
    /// reservation, since the real cost is unknown.
    Broken { reason: String, cost_usd_micros: u64, tokens: u64 },
}

/// Tokens a call used, as the provider reported them.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Usage {
    pub input: u64,
    pub output: u64,
    pub cache_write: u64,
    pub cache_read: u64,
}

impl Usage {
    pub fn total(&self) -> u64 {
        self.input + self.output + self.cache_write + self.cache_read
    }
}

/// A journaled event with its position and time.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Entry {
    /// 1 for the first entry, then consecutive.
    pub seq: u64,
    pub ts_ms: u64,
    pub event: Event,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Writes `Methods.ts` and `Notifications.ts` next to the ts-rs bindings. Runs with the other
    /// ts-rs export tests under `cargo test`.
    #[test]
    fn export_methods_map() {
        let dir = std::env::var("TS_RS_EXPORT_DIR").expect("set by .cargo/config.toml");
        std::fs::create_dir_all(&dir).unwrap();
        let dir = std::path::Path::new(&dir);
        std::fs::write(dir.join("Methods.ts"), typescript_methods()).unwrap();
        std::fs::write(dir.join("Notifications.ts"), typescript_notifications()).unwrap();
    }

    #[test]
    fn method_names_are_unique() {
        let mut names = METHOD_NAMES.to_vec();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), METHOD_NAMES.len());
    }

    /// The well-known SHA-256 of "hello".
    const HELLO_HEX: &str = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824";

    #[test]
    fn digests_round_trip_through_their_string_form() {
        let s = format!("sha256:{HELLO_HEX}");
        let d = Digest::parse(&s).unwrap();
        assert_eq!(d.hex(), HELLO_HEX);
        assert_eq!(d.to_string(), s);
        assert_eq!(serde_json::to_string(&d).unwrap(), format!("\"{s}\""));
        assert_eq!(serde_json::from_str::<Digest>(&format!("\"{s}\"")).unwrap(), d);
    }

    #[test]
    fn digests_parse_only_their_own_format() {
        for bad in [
            format!("md5:{HELLO_HEX}"),
            "sha256:2cf24dba".to_string(),
            format!("sha256:{HELLO_HEX}00"),
            format!("sha256:zz{}", &HELLO_HEX[2..]),
            HELLO_HEX.to_string(),
            format!("sha256:{}", HELLO_HEX.to_uppercase()),
        ] {
            assert_eq!(Digest::parse(&bad), None, "{bad} should not parse");
        }
        assert!(serde_json::from_str::<Digest>("\"sha256:nope\"").is_err());
    }

    #[test]
    fn empty_is_an_object() {
        assert_eq!(serde_json::to_string(&Empty {}).unwrap(), "{}");
    }
}
