//! The strive wire protocol.
//!
//! Clients (the TUI, the Electron app, the agent host, headless runs) talk to
//! `strived` with JSON-RPC 2.0, one JSON object per line, over a Unix socket.
//! Every method is declared once in [`methods!`]; that declaration produces the
//! Rust types, the [`Method`] impl and the TypeScript `Methods` map, so the two
//! sides cannot drift without the drift check failing.

pub mod rpc;

use serde::{Deserialize, Serialize, de::DeserializeOwned};
use ts_rs::TS;

/// Bumped on any incompatible change. Clients and daemon must agree exactly.
pub const PROTOCOL_VERSION: u32 = 1;

/// A request method: its wire name plus parameter and result types.
pub trait Method {
    const NAME: &'static str;
    type Params: Serialize + DeserializeOwned;
    type Result: Serialize + DeserializeOwned;
}

macro_rules! methods {
    ($($ty:ident = $name:literal ($params:ty) -> $result:ty;)*) => {
        $(
            #[doc = concat!("The `", $name, "` method.")]
            pub enum $ty {}
            impl Method for $ty {
                const NAME: &'static str = $name;
                type Params = $params;
                type Result = $result;
            }
        )*

        /// Every method name, in declaration order.
        pub const METHOD_NAMES: &[&str] = &[$($name),*];

        /// TypeScript source for the `Methods` map used by the typed client.
        pub fn typescript_methods() -> String {
            let mut imports = std::collections::BTreeSet::new();
            let mut body = String::new();
            $(
                for t in [<$params as TS>::name(&ts_rs::Config::default()), <$result as TS>::name(&ts_rs::Config::default())] {
                    if t != "null" { imports.insert(t); }
                }
                body.push_str(&format!(
                    "  {:?}: {{ params: {}; result: {} }};\n",
                    $name,
                    <$params as TS>::name(&ts_rs::Config::default()),
                    <$result as TS>::name(&ts_rs::Config::default()),
                ));
            )*
            let mut out = String::from("// Generated by strive-proto. Do not edit.\n");
            for t in imports {
                out.push_str(&format!("import type {{ {t} }} from \"./{t}\";\n"));
            }
            out.push_str("\nexport type Methods = {\n");
            out.push_str(&body);
            out.push_str("};\n\nexport type MethodName = keyof Methods;\n");
            out.push_str(&format!("\nexport const PROTOCOL_VERSION = {};\n", PROTOCOL_VERSION));
            out
        }
    };
}

methods! {
    Initialize = "initialize" (InitializeParams) -> InitializeResult;
    DaemonStatus = "daemon/status" (Empty) -> DaemonStatusResult;
    DaemonShutdown = "daemon/shutdown" (Empty) -> Empty;
    SessionCreate = "session/create" (SessionCreateParams) -> SessionInfo;
    SessionList = "session/list" (SessionListParams) -> SessionListResult;
    SessionAttach = "session/attach" (SessionAttachParams) -> SessionAttachResult;
    SessionPrompt = "session/prompt" (SessionPromptParams) -> Appended;
    SessionRead = "session/read" (SessionRef) -> SessionReadResult;
    SessionGateway = "session/gateway" (SessionRef) -> GatewayInfo;
    SessionBudget = "session/budget" (SessionBudgetParams) -> Appended;
    AuthSet = "auth/set" (AuthSetParams) -> Empty;
    AuthStatus = "auth/status" (Empty) -> AuthStatusResult;
        EffectRun = "effect/run" (EffectRunParams) -> EffectRunResult;
    EffectCancel = "effect/cancel" (EffectCancelParams) -> Empty;
    BlobGet = "blob/get" (BlobGetParams) -> BlobGetResult;
    SessionApprovals = "session/approvals" (SessionApprovalsParams) -> Appended;
            ApprovalRespond = "approval/respond" (ApprovalRespondParams) -> Empty;
    SessionRewind = "session/rewind" (SessionRewindParams) -> SessionRewindResult;
    SessionChanges = "session/changes" (SessionChangesParams) -> SessionChangesResult;
    LearningOpen = "learning/open" (ProjectRef) -> SessionInfo;
    LearningRun = "learning/run" (LearningRunParams) -> Appended;
    ProposalList = "proposal/list" (ProjectRef) -> ProposalListResult;
    ProposalDecide = "proposal/decide" (ProposalDecideParams) -> Appended;
    ProposalRollback = "proposal/rollback" (ProposalRef) -> Appended;
    HostRegister = "host/register" (SessionRef) -> AgentConfig;
    HostRecord = "host/record" (HostRecordParams) -> Appended;
    HostStream = "host/stream" (HostStreamParams) -> Empty;
    SessionInterrupt = "session/interrupt" (SessionRef) -> Empty;
    ModelList = "model/list" (Empty) -> ModelListResult;
    SessionModel = "session/model" (SessionModelParams) -> Appended;
}

/// A server-to-client notification: its wire name plus payload type.
pub trait Notification {
    const NAME: &'static str;
    type Params: Serialize + DeserializeOwned;
}

macro_rules! notifications {
    ($($(#[$doc:meta])* $ty:ident = $name:literal ($params:ty);)*) => {
        $(
            $(#[$doc])*
            pub enum $ty {}
            impl Notification for $ty {
                const NAME: &'static str = $name;
                type Params = $params;
            }
        )*

        /// TypeScript source for the `Notifications` map.
        pub fn typescript_notifications() -> String {
            let mut out = String::from("// Generated by strive-proto. Do not edit.\n");
            $(
                let t = <$params as TS>::name(&ts_rs::Config::default());
                out.push_str(&format!("import type {{ {t} }} from \"./{t}\";\n"));
            )*
            out.push_str("\nexport type Notifications = {\n");
            $(
                out.push_str(&format!("  {:?}: {};\n", $name, <$params as TS>::name(&ts_rs::Config::default())));
            )*
            out.push_str("};\n\nexport type NotificationName = keyof Notifications;\n");
            out
        }
    };
}

notifications! {
        /// A new entry in a session this connection attached to.
    SessionEntry = "session/entry" (SessionEntryNotification);
    /// The model's reply so far, while it streams.
    SessionDelta = "session/delta" (SessionDeltaNotification);
    /// Sent to the session's host: stop the current turn.
    SessionInterruptRequested = "session/interrupt" (SessionInterruptNotification);
}

/// Parameters or result with no fields. Serializes as `{}`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Empty {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ClientInfo {
    /// For example `strive-tui`, `strive-desktop`, `strive-host`.
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InitializeParams {
    pub protocol_version: u32,
    pub client: ClientInfo,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ServerInfo {
    pub version: String,
    /// Identifies the exact daemon binary, so a rebuilt or upgraded `strive`
    /// can tell that the running daemon is stale.
    pub build: String,
    pub pid: u32,
    pub started_at_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InitializeResult {
    pub protocol_version: u32,
    pub server: ServerInfo,
    /// The strive home directory, `~/.strive` unless `STRIVE_HOME` is set.
    pub home: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DaemonStatusResult {
    pub server: ServerInfo,
    pub uptime_ms: u64,
    /// Connected clients, including the caller.
    pub clients: u32,
    /// Seconds with no clients before the daemon exits.
    pub idle_exit_secs: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionInfo {
    pub id: String,
    pub cwd: String,
    pub created_at_ms: u64,
    /// The session's first prompt, shortened: what a list calls it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub title: Option<String>,
    /// When its journal last changed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub last_active_ms: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub kind: Option<SessionKind>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionCreateParams {
    pub cwd: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionListParams {
    /// Only sessions started in this directory. All sessions when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub cwd: Option<String>,
    /// Only sessions of this kind; work sessions when absent, so the lists
    /// people pick a session from never offer a project's learner.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub kind: Option<SessionKind>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionListResult {
    /// Newest first.
    pub sessions: Vec<SessionInfo>,
    /// Sessions whose journal can't be read far enough to know their
    /// directory. Listed only when not filtering by directory.
    pub unreadable: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionRef {
    pub id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionAttachParams {
    pub id: String,
    /// Return only entries after this seq (for catching up after a reconnect).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub after_seq: Option<u64>,
    /// Watching, not someone who can approve (a headless run): approval
    /// requests don't wait for this client.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub observer: Option<bool>,
}

/// History up to now. Later entries arrive as `session/entry` notifications.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionAttachResult {
    pub session: SessionInfo,
    pub entries: Vec<Entry>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionPromptParams {
    pub id: String,
    pub text: String,
}

/// The seq of the entry a request appended.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Appended {
    pub seq: u64,
}

/// Where a session's model calls go. Each URL embeds a secret token scoped to
/// the session, so give it only to that session's agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GatewayInfo {
    /// Base URL for the Anthropic SDK (it appends `/v1/messages`).
    pub anthropic: String,
    /// Base URL for the OpenAI SDK (it appends `/chat/completions` or `/responses`).
    pub openai: String,
}

/// Replaces the session's limits. An absent limit means unlimited.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionBudgetParams {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub usd_micros: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub tokens: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AuthSetParams {
    /// `anthropic` or `openai`.
    pub provider: String,
    pub api_key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AuthStatusResult {
    pub providers: Vec<ProviderAuth>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProviderAuth {
    pub provider: String,
    /// Where the key came from: `file` (strive auth), `env` (the daemon's
    /// environment when it started), or `none`.
    pub source: String,
}

/// The models the gateway will price, so an agent can use them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ModelListResult {
    /// By id.
    pub models: Vec<ModelInfo>,
    /// The model in settings: what a session uses unless one is chosen.
    pub default: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ModelInfo {
    pub id: String,
    /// `anthropic` or `openai`: whose key its calls need.
    pub provider: String,
    pub context_window: u64,
    /// Micro-dollars per million tokens.
    pub input_usd_micros: u64,
    pub output_usd_micros: u64,
}

/// Chooses the model a session's agent starts with. Refused once the
/// session has a prompt: its agent may already be running on another.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionModelParams {
    pub id: String,
    pub model: String,
}

/// A session's journal as it is on disk, and whether it verifies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionReadResult {
    pub session: SessionInfo,
    /// The entries that verified, in order.
    pub entries: Vec<Entry>,
    pub committed: u64,
    /// Bytes of a partial last line left by a crash; discarded on next open.
    pub torn_bytes: u64,
    /// Why verification failed. Absent when the journal is intact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub problem: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionEntryNotification {
    pub session_id: String,
    pub entry: Entry,
}

/// The SHA-256 of a blob in the content store, written `sha256:<64 lowercase hex>`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, TS)]
#[ts(export, type = "string")]
pub struct Digest([u8; 32]);

impl Digest {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    pub fn parse(s: &str) -> Option<Self> {
        let hex = s.strip_prefix("sha256:")?;
        if hex.len() != 64 || hex.bytes().any(|b| b.is_ascii_uppercase()) {
            return None;
        }
        let mut out = [0u8; 32];
        hex::decode_to_slice(hex, &mut out).ok()?;
        Some(Self(out))
    }

    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// The 64-character lowercase hex form, without the `sha256:` prefix.
    pub fn hex(&self) -> String {
        hex::encode(self.0)
    }
}

impl std::fmt::Display for Digest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "sha256:{}", self.hex())
    }
}

impl Serialize for Digest {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.collect_str(self)
    }
}

impl<'de> Deserialize<'de> for Digest {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = String::deserialize(d)?;
        Digest::parse(&s).ok_or_else(|| serde::de::Error::custom(format!("not a sha256 digest: {s:?}")))
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct EffectRunParams {
    pub id: String,
    pub call_id: String,
    pub request: EffectRequest,
}

/// Stops an effect the agent no longer wants: one waiting for approval is
/// refused, and a running command is killed. Cancelling one that has already
/// finished (or not yet started) is not an error.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct EffectCancelParams {
    pub id: String,
    pub call_id: String,
}

/// The effect's journal number and outcome, with the output text inline.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct EffectRunResult {
    pub effect: u64,
    pub outcome: EffectOutcome,
    /// The output (for `done`) or the reason (for `refused`), as the agent sees it.
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionApprovalsParams {
    pub id: String,
    pub mode: ApprovalMode,
}

/// What the agent host needs to run a session's agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AgentConfig {
    pub cwd: String,
    pub model: String,
    /// `anthropic` or `openai`.
    pub provider: String,
    /// The gateway base URL for that provider (holds the session's token).
    pub base_url: String,
    pub context_window: u64,
    pub max_output: u64,
    pub turn_seconds: u64,
    /// Summarize the conversation before a turn once it is estimated to be
    /// this many tokens.
    pub compact_at_tokens: u64,
    /// Instruction files (AGENTS.md, CLAUDE.md), outermost first.
    pub instructions: Vec<InstructionFile>,
    pub skills: Vec<SkillInfo>,
    /// Tools from the MCP servers that started. The agent calls them as
    /// `mcp` effects.
    pub mcp_tools: Vec<McpTool>,
    /// What the session is for: a learning session's host runs the learner.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub kind: Option<SessionKind>,
    /// For the learner only: the project's memory and skills, each file's
    /// whole text exactly as it is, so it can propose a whole new file. A
    /// file missing here didn't exist (or can't be proposed over: not a
    /// regular file, reached through a symlink, or over 64 KiB). Accepting
    /// a proposal writes only over the file as given here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub learned_files: Option<Vec<LearnedFile>>,
}

/// A memory or skill file as the learner is shown it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct LearnedFile {
    pub artifact: Artifact,
    pub text: String,
}

/// What a session is for.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum SessionKind {
    /// A person's work with the agent.
    #[default]
    Work,
    /// The project's learner: it studies work sessions and proposes changes
    /// to the agent's memory and skills, which people review.
    Learning,
    /// One run of the replay gate (ADR-0018): a past task, run again by the
    /// daemon in a scratch copy of the project, with or without a proposal.
    Replay,
}

/// A project: the directory its sessions work in.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProjectRef {
    pub cwd: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct LearningRunParams {
    pub cwd: String,
    /// Work sessions to study; none: those since the learner last looked.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub sessions: Option<Vec<String>>,
}

/// A change the learner proposes: a whole file's new text, why, the
/// evidence, and what should happen if it's right.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Proposal {
    pub artifact: Artifact,
    /// The file's whole new text. Memory and skills are small; a whole file
    /// can be checked, shown and undone exactly.
    pub content: String,
    /// One line: what it changes, for a list.
    pub summary: String,
    /// Why, in the learner's words.
    pub rationale: String,
    /// The sessions (and entries in them) that led to it.
    pub evidence: Vec<Evidence>,
    /// A falsifiable claim about what the change will do, checked later.
    pub prediction: String,
}

/// What a proposal changes. Paths are fixed by kind, inside the project:
/// memory is `.strive/memory.md`, a skill `.strive/skills/<name>/SKILL.md`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", tag = "kind")]
#[ts(export)]
pub enum Artifact {
    Memory,
    Skill { name: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Evidence {
    pub session: String,
    /// Entries in it, by seq.
    #[serde(default)]
    pub seqs: Vec<u64>,
    /// What those entries show.
    pub note: String,
}

/// A check a proposal goes through before a person sees it as ready.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum Gate {
    /// The daemon's own checks: path, size, secrets, instructions that
    /// would weaken strive's safeguards.
    Static,
    /// A model, outside the learner's authority, judging it against
    /// sessions the learner didn't see.
    Judge,
    /// Past tasks run again with and without it.
    Replay,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum Verdict {
    Pass,
    Fail,
    /// Not run, and why is in the detail.
    Skipped,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ProposalDecision {
    Accept,
    Reject,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProposalRef {
    pub cwd: String,
    pub proposal: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProposalDecideParams {
    pub cwd: String,
    pub proposal: u64,
    pub decision: ProposalDecision,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProposalListResult {
    /// Newest first.
    pub proposals: Vec<ProposalState>,
    /// The project's learned files, by path in it, that aren't what an
    /// accepted proposal last left there: changed outside review (by hand,
    /// by git), or there with no applied proposal behind them.
    #[serde(default)]
    pub changed_outside_review: Vec<String>,
}

/// A proposal as it stands, folded from the learning session's journal.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProposalState {
    pub id: u64,
    pub made_at_ms: u64,
    pub proposal: Proposal,
    /// The file as the learner was shown it, in the content store (none: it
    /// didn't exist). Its diff is from this to the new content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub before: Option<Digest>,
    pub status: ProposalStatus,
    pub gates: Vec<GateOutcome>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GateOutcome {
    pub gate: Gate,
    pub verdict: Verdict,
    pub detail: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ProposalStatus {
    /// Checks still running.
    Checking,
    /// Every check passed or was skipped; waiting for a person.
    Ready,
    /// A check failed; a person may still look, but it can't be accepted.
    Failed,
    Rejected,
    /// Accepted and written.
    Applied,
    /// Accepted, but the file had changed since it was proposed, so it
    /// wasn't written.
    Stale,
    RolledBack,
}

/// An event the host records: turns, assistant messages and summaries; a
/// work session's host also layout proposals, a learning session's host
/// `proposalMade`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HostRecordParams {
    pub id: String,
    pub event: Event,
}

/// Live text from the model, shown while it streams; not journaled.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HostStreamParams {
    pub id: String,
    pub turn: u64,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionDeltaNotification {
    pub session_id: String,
    pub turn: u64,
    /// The reply's text so far.
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionInterruptNotification {
    pub session_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionRewindParams {
    pub id: String,
    pub checkpoint: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionRewindResult {
    /// The checkpoint holding the files as they were before the rewind.
    pub saved_as: u64,
    /// Nested repositories, left as they were: checkpoints don't hold them.
    pub not_saved: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionChangesParams {
    pub id: String,
    /// Changes since this checkpoint, to the files as they are now.
    pub checkpoint: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SessionChangesResult {
    /// Changed files, by path.
    pub files: Vec<FileChange>,
    /// More files changed than are listed.
    pub more: bool,
}

/// One file's change: its text before and after, when it's text and not too
/// large to show (checkpoints don't save ignored files or nested repositories,
/// so those never appear).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct FileChange {
    pub path: String,
    pub status: ChangeStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub before: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub after: Option<String>,
    /// Binary, or too large to show; only its status is known.
    pub opaque: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ChangeStatus {
    Added,
    Modified,
    Deleted,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ApprovalRespondParams {
    pub id: String,
    pub effect: u64,
    pub decision: Decision,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct BlobGetParams {
    pub digest: Digest,
}

/// A blob as UTF-8 text (lossily converted if it isn't).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct BlobGetResult {
    pub text: String,
    pub bytes: u64,
}

/// Something that happened in a session. Journaled in order; never edited.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum Event {
    SessionStarted {
        /// Journal format version.
        format: u32,
        cwd: String,
        strive_version: String,
        /// What the session is for; a work session when absent.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        kind: Option<SessionKind>,
    },
    UserMessage {
        text: String,
    },
    /// Opening the journal found a partial last line from a crash and
    /// discarded it.
    Recovered {
        discarded_bytes: u64,
    },
    /// The session's spending limits from here on. `None` means unlimited.
    BudgetSet {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        usd_micros: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        tokens: Option<u64>,
    },
    /// A model request was admitted against the budget and sent upstream.
    /// Written before sending, so a crash mid-call still counts it.
    ModelCallStarted {
        /// Numbers this session's calls; pairs with `ModelCallFinished`.
        call: u64,
        provider: String,
        model: String,
        /// The exact request body sent upstream.
        request: Digest,
        /// The most this call can cost, held until it finishes.
        reserved_usd_micros: u64,
        reserved_tokens: u64,
    },
    ModelCallFinished {
        call: u64,
        outcome: CallOutcome,
        /// The exact response bytes received, when any were.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        response: Option<Digest>,
        duration_ms: u64,
    },
    /// The daemon is about to perform a change or command for the agent.
    /// Written first, so an effect cut off by a crash is still on record.
    EffectStarted {
        /// Numbers this session's effects; pairs with `EffectFinished`.
        effect: u64,
        /// The model's tool call this effect serves.
        call_id: String,
        record: EffectRecord,
    },
    EffectFinished {
        effect: u64,
        outcome: EffectOutcome,
        duration_ms: u64,
    },
    /// What the agent may do without asking, from here on.
    ApprovalModeSet {
        mode: ApprovalMode,
    },
    /// An effect waits for a person to allow or decline it.
    ApprovalRequested {
        effect: u64,
        description: String,
    },
    ApprovalDecided {
        effect: u64,
        decision: Decision,
        /// The client that decided.
        by: String,
    },
    /// The workspace's files were saved (outside the user's own git).
    Checkpointed {
        checkpoint: u64,
        /// The commit in the session's shadow repository.
        commit: String,
    },
    /// The workspace was put back to a checkpoint; the files as they were
    /// just before are checkpoint `saved_as`, so this can be undone.
    Rewound {
        to: u64,
        saved_as: u64,
    },
    /// The agent began working on the session's prompts.
    TurnStarted {
        turn: u64,
        /// The last prompt this turn took: later ones wait for the next turn,
        /// even if they were journaled before this entry.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        through_seq: Option<u64>,
    },
    /// The model's reply within a turn.
    AssistantMessage {
        turn: u64,
        /// The reply's text, for showing.
        text: String,
        /// The tools it called; their results are the effects with these ids.
        tool_calls: Vec<ToolCall>,
        /// The message exactly as the agent keeps it, fed back on resume.
        #[ts(type = "unknown")]
        message: serde_json::Value,
    },
    TurnEnded {
        turn: u64,
        reason: TurnEnd,
    },
    /// The project context an agent host was given when it started.
    ContextLoaded {
        instructions: Vec<ContextFile>,
        skills: Vec<String>,
        /// MCP servers from settings, and how each started.
        #[serde(default)]
        mcp: Vec<McpStatus>,
        /// A learning session's only: the memory and skill files its host
        /// was given (`AgentConfig.learnedFiles`), by path in the project.
        /// A proposal's `before` is the file as last given here.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        learned: Option<Vec<ContextFile>>,
    },
    /// A person asked the project's learner to study sessions (none named:
    /// the ones since it last looked). Journaled in the learning session;
    /// its host takes it as a prompt.
    LearnRequested {
        /// The work sessions to study; empty: those since the learner last looked.
        #[serde(default)]
        sessions: Vec<String>,
    },
    /// The learner proposed a change to what the agent is given (its memory
    /// or a skill). Nothing changes until a person accepts it. Its id is
    /// this entry's seq.
    ProposalMade {
        /// The learner's tool call that made it, whose result it is.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        call_id: Option<String>,
        proposal: Proposal,
        /// The file as the learner was last shown it (`contextLoaded`'s
        /// `learned`), in the content store; none: it didn't exist.
        /// Recorded by the daemon, never the host: accepting writes only
        /// over this same file.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        before: Option<Digest>,
    },
    /// A check of a proposal finished.
    GateFinished {
        proposal: u64,
        gate: Gate,
        verdict: Verdict,
        /// What it found, for a person reviewing the proposal.
        detail: String,
    },
    /// The replay gate began on a proposal (ADR-0018), holding up to
    /// `reserved_usd_micros` of this learning session's budget until
    /// `ReplayFinished`. A hold that never finishes stays charged in full.
    ReplayStarted {
        proposal: u64,
        reserved_usd_micros: u64,
    },
    /// The replay gate's runs are over: what they cost is charged in place of
    /// the hold, and each run's session is named for audit.
    ReplayFinished {
        proposal: u64,
        cost_usd_micros: u64,
        tokens: u64,
        runs: Vec<ReplayRun>,
    },
    /// A person accepted or rejected a proposal.
    ProposalDecided {
        proposal: u64,
        decision: ProposalDecision,
        /// The client that decided.
        by: String,
    },
    /// An accepted proposal was written: the file as it was (none if it
    /// didn't exist) and as it is now.
    ProposalApplied {
        proposal: u64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        before: Option<Digest>,
        after: Digest,
    },
    /// An applied proposal was undone: the file is back as it was.
    ProposalRolledBack {
        proposal: u64,
        by: String,
    },
    /// The agent proposed a change to the desktop workspace's layout. It
    /// changes nothing until a person accepts it in the desktop app.
    LayoutProposed {
        /// The agent's tool call that made the proposal, whose result it is.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        call_id: Option<String>,
        label: String,
        /// The workspace ops, as the agent gave them; the app parses them.
        #[ts(type = "unknown")]
        ops: serde_json::Value,
    },
    /// The conversation up to entry `upto_seq` was summarized; from here on
    /// the agent carries the summary instead of those messages.
    Compacted {
        upto_seq: u64,
        summary: String,
    },
    /// The model this session's agent uses, in place of the one in settings.
    /// Chosen before the first prompt, since the agent starts with it.
    ModelSet {
        model: String,
    },
}

/// One run of a replayed task.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ReplayRun {
    /// The replay session that ran it.
    pub session: String,
    /// The work session the task was mined from, and its prompt's seq.
    pub task_session: String,
    pub task_seq: u64,
    /// Whether the proposal's file was in place.
    pub with_change: bool,
    /// Whether the task's check command exited 0 afterwards.
    pub passed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ContextFile {
    pub path: String,
    /// The text as given to the agent (imports inlined), in the content store.
    pub digest: Digest,
    pub bytes: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InstructionFile {
    pub path: String,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct McpTool {
    pub server: String,
    pub name: String,
    pub description: String,
    /// The tool's JSON Schema for its arguments, as the server gave it.
    #[ts(type = "unknown")]
    pub input_schema: serde_json::Value,
}

/// How an MCP server fared when a session's agent started.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct McpStatus {
    pub server: String,
    pub tools: u64,
    /// Why it didn't start, if it didn't.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SkillInfo {
    pub name: String,
    pub description: String,
    /// Its SKILL.md, which the agent reads when the skill applies.
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
}

/// Why a turn ended.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum TurnEnd {
    /// The model finished.
    Done,
    /// Someone interrupted it.
    Interrupted,
    /// It ran past the session's time limit for a turn.
    TimedOut { seconds: u64 },
    /// A model call failed (budget, provider error, ...).
    Failed { error: String },
}

/// What the agent may do without asking. Writes outside the workspace
/// always ask; strive's own state is never allowed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ApprovalMode {
    /// Reading is free; every change and command asks.
    Ask,
    /// Changes inside the workspace are free; commands ask.
    AutoEdit,
    /// Everything inside the workspace and the sandbox is free.
    FullAuto,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum Decision {
    Allow,
    /// Allow this and switch the session to full-auto.
    AllowSession,
    Deny,
}

/// What the agent asked the daemon to do, as the protocol carries it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum EffectRequest {
    /// Lines `offset..offset+limit` of a text file (1-based; defaults to the start).
    Read {
        path: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        limit: Option<u64>,
    },
    /// Replaces the whole file, creating it and its directories if needed.
    Write { path: String, content: String },
    /// Replaces the one occurrence of `old_text` with `new_text`.
    Edit { path: String, old_text: String, new_text: String },
    /// Calls a tool on one of the session's MCP servers.
    Mcp {
        server: String,
        tool: String,
        #[ts(type = "unknown")]
        arguments: serde_json::Value,
    },
    /// Runs a shell command in the session's directory, in the sandbox.
    Bash {
        command: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        timeout_ms: Option<u64>,
    },
}

/// An effect as the journal records it: large payloads live in the content
/// store and are named by digest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum EffectRecord {
    Read {
        path: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        offset: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        limit: Option<u64>,
    },
    Write {
        path: String,
        content: Digest,
        bytes: u64,
    },
    Edit {
        path: String,
        old_text: Digest,
        new_text: Digest,
    },
    Bash {
        command: String,
        timeout_ms: u64,
    },
    Mcp {
        server: String,
        tool: String,
        /// The arguments, as JSON.
        arguments: Digest,
    },
}

/// How an effect ended. `output` is what the agent is shown.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum EffectOutcome {
    /// It ran. For bash, `exit_code` is the command's status (absent if it
    /// was killed by the timeout).
    Done {
        output: Digest,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        exit_code: Option<i32>,
        /// The output was cut to fit; the full output isn't kept.
        truncated: bool,
    },
    /// It was not allowed, or could not be done; `reason` says why.
    Refused { reason: String },
    /// The daemon stopped while it ran; whatever it changed stays changed.
    Interrupted,
}
/// How a model call ended, and what it cost.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase", rename_all_fields = "camelCase")]
#[ts(export)]
pub enum CallOutcome {
    /// The provider reported usage; the cost is exact.
    Complete { status: u16, usage: Usage, cost_usd_micros: u64 },
    /// The provider refused the request before doing work (an error status).
    Rejected { status: u16 },
    /// The call broke after it may have been billed. It is charged the full
    /// reservation, since the real cost is unknown.
    Broken { reason: String, cost_usd_micros: u64, tokens: u64 },
}

/// Tokens a call used, as the provider reported them.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Usage {
    pub input: u64,
    pub output: u64,
    /// Cache writes at the standard (five-minute) rate.
    pub cache_write: u64,
    /// Cache writes kept for an hour, at their higher rate.
    #[serde(default)]
    pub cache_write_long: u64,
    pub cache_read: u64,
}

impl Usage {
    pub fn total(&self) -> u64 {
        self.input
            .saturating_add(self.output)
            .saturating_add(self.cache_write)
            .saturating_add(self.cache_write_long)
            .saturating_add(self.cache_read)
    }
}

/// A journaled event with its position and time.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Entry {
    /// 1 for the first entry, then consecutive.
    pub seq: u64,
    pub ts_ms: u64,
    pub event: Event,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Writes `Methods.ts` and `Notifications.ts` next to the ts-rs bindings. Runs with the other
    /// ts-rs export tests under `cargo test`.
    #[test]
    fn export_methods_map() {
        let dir = std::env::var("TS_RS_EXPORT_DIR").expect("set by .cargo/config.toml");
        std::fs::create_dir_all(&dir).unwrap();
        let dir = std::path::Path::new(&dir);
        std::fs::write(dir.join("Methods.ts"), typescript_methods()).unwrap();
        std::fs::write(dir.join("Notifications.ts"), typescript_notifications()).unwrap();
    }

    #[test]
    fn method_names_are_unique() {
        let mut names = METHOD_NAMES.to_vec();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), METHOD_NAMES.len());
    }

    /// The well-known SHA-256 of "hello".
    const HELLO_HEX: &str = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824";

    #[test]
    fn digests_round_trip_through_their_string_form() {
        let s = format!("sha256:{HELLO_HEX}");
        let d = Digest::parse(&s).unwrap();
        assert_eq!(d.hex(), HELLO_HEX);
        assert_eq!(d.to_string(), s);
        assert_eq!(serde_json::to_string(&d).unwrap(), format!("\"{s}\""));
        assert_eq!(serde_json::from_str::<Digest>(&format!("\"{s}\"")).unwrap(), d);
    }

    #[test]
    fn digests_parse_only_their_own_format() {
        for bad in [
            format!("md5:{HELLO_HEX}"),
            "sha256:2cf24dba".to_string(),
            format!("sha256:{HELLO_HEX}00"),
            format!("sha256:zz{}", &HELLO_HEX[2..]),
            HELLO_HEX.to_string(),
            format!("sha256:{}", HELLO_HEX.to_uppercase()),
        ] {
            assert_eq!(Digest::parse(&bad), None, "{bad} should not parse");
        }
        assert!(serde_json::from_str::<Digest>("\"sha256:nope\"").is_err());
    }

    #[test]
    fn empty_is_an_object() {
        assert_eq!(serde_json::to_string(&Empty {}).unwrap(), "{}");
    }
}
